name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint (ruff)
        run: poetry run ruff .
      - name: Lint (black)
        run: poetry run black --check .
      - name: Security (bandit)
        run: poetry run bandit -r .
      - name: Test (pytest)
        run: poetry run pytest tests/unit
      - name: Build Docker images
        run: docker-compose build
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker images
        run: docker-compose push
